version: '3'

services:
  db:
    image: redis
    env_file:
      - .env
    container_name: redis-db
    hostname: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
  api:
    build: 
      context: .
      dockerfile: api.Dockerfile
    env_file:
      - .env
    container_name: url-shortener-api
    restart: always
    networks:
      - default
    ports:
      - "${PORT}:${PORT}"
    links:
      - db
    depends_on:
      - db
